spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libraryApi_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  flyway:
    clean-on-validation-error: false
    locations: classpath:db/migration