CREATE TABLE loans
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    loaned_at TIMESTAMP DEFAULT NOW(),
    due_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    loan_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT pk_loans PRIMARY KEY (id),
    CONSTRAINT fk_loans_books FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_loans_users FOREIGN KEY (user_id) REFERENCES users (id)
)